@startuml
title Cocina
left to right direction
skinparam packageStyle rectangle
actor usuario

rectangle cocina{

    (consultar códigos qr) ..> (generar códigos qr) : include
    (generar códigos qr) <.. (editar códigos qr) : extends
    (generar códigos qr) <.. (borrar códigos qr) : extends

    usuario -- (consultar códigos qr)
    usuario -- (buscar receta)
    usuario -- (crear receta)
    (buscar receta) .> (crear receta) : include
    (buscar receta) <.. (realizar receta) : extends
    (crear receta) <.. (realizar receta) : extends
    (buscar receta) <.. (compartir receta) : extends
    (crear receta) <.. (compartir receta) : extends

    (alta usuario) -- usuario
    (agregar a favoritos) ..> (alta usuario) : extends
    (buscar receta) <.. (agregar a favoritos) : include
    (puntuar receta) ..> (alta usuario) : extends
    (realizar receta) <.. (puntuar receta) : include
    (publicar receta) ..> (alta usuario) : extends
    (crear receta) <.. (publicar receta) : include
    (borrar receta) ..> (alta usuario) : extends
    (crear receta) <.. (borrar receta) : include
    (descargar receta) ..> (alta usuario) : extends
    (buscar receta) <.. (descargar receta) : include
    (editar receta) ..> (descargar receta) : extends
    (crear receta) ..> (editar receta) : extends

    (alta usuario) <.. (generar menú) : extends
    (borrar menú) .> (generar menú) : extends
    (alta usuario) <.. (consultar menú) : extends
    (consultar menú) <. (descargar menú) : extends
    (descargar menú) <. (generar lista) : extends

}

@enduml